### ISSUE TITLE
Erro via boleto

### ISSUE THREAD

**Issue by pedroohsolucoes** [gerencianet/gn-api-magento2#5]
Olá, estou tendo um erro ao tentar realizar a compra com boleto:

"Fatal Error: 'Uncaught Error: Class 'Gerencianet\\Gerencianet' not found in \/home\/csm\/public_html\/lojas\/teste-m235\/app\/code\/Gerencianet\/Magento2\/Model\/Payment\/Billet.php:166\nStack trace:\n#0 \/home\/csm\/public_html\/lojas\/teste-m235\/vendor\/magento\/module-sales\/Model\/Order\/Payment\/Operations\/OrderOperation.php(35): Gerencianet\\Magento2\\Model\\Payment\\Billet->order(Object(Magento\\Sales\\Model\\Order\\Payment\\Interceptor), 10)\n#1 \/home\/csm\/public_html\/lojas\/teste-m235\/vendor\/magento\/module-sales\/Model\/Order\/Payment\/Processor.php(97): Magento\\Sales\\Model\\Order\\Payment\\Operations\\OrderOperation->order(Object(Magento\\Sales\\Model\\Order\\Payment\\Interceptor), 10)\n#2 \/home\/csm\/public_html\/lojas\/teste-m235\/vendor\/magento\/module-sales\/Model\/Order\/Payment.php(1105): Magento\\Sales\\Model\\Order\\Payment\\Processor->order(Object(Magento\\Sales\\Model\\Order\\Payment\\Interceptor), 10)\n#3 \/home\/csm\/public_html\/lojas\/teste-m235\/vendor\/magento\/module-sales\/Model\/Order\/Payment.php(444): Magento\\Sales\\Model\\Order\\Payment->_order(10)\n#4 \/home\/csm\/public_html\/lo' in '\/home\/csm\/public_html\/lojas\/teste-m235\/app\/code\/Gerencianet\/Magento2\/Model\/Payment\/Billet.php' on line 166"

**Comment by pedroohsolucoes** [comment]
Resolvido instalando o SDK
Instale o SDK PHP da Gerencianet
